default: &default
  enabled: true
  site_id:
    # "<decidim_organizations.name>" : "polis_site_id_XXXXXXXXXX"
    "Test_Paul_hîsse": "polis_site_id_A29i1s5PR6ggeaMwgb"
    "Developement": "polis_site_id_A29i1s5PR6ggeaMwgb"
    "fedict": "polis_site_id_A29i1s5PR6ggeaMwgb"
    "test 03": "yuteyaegdvs"

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
