default: &default
  enabled: true
  site_id:
    # "<decidim_organizations.name>" : "polis_site_id_XXXXXXXXXX"
    "Test_Paul_hîsse": "polis_site_id_XXXXXXXXXXXXXX"
    "Developement": "polis_site_id_XXXXXXXXXXXXXXXXX"
    "fedict": "polis_site_id_XXXXXXXXXXXXXXXXX"
  fr:
    "titre_message": "Participer au débat"
    "texte_message_1": "Pour participer au débat"
    "lien_message_1": "connectez vous avec votre compte"
    "texte_message_2": "ou"
    "lien_message_2": "inscrivez vous"
    "titre_help_1": "Comment ça marche ?"
    "titre_help_2": "Bienvenue sur un nouveau type de discussion."
    "help_1": "Votez sur les opinions des autres."
    "help_2": "Exprimez la votre."
    "help_3": "A partir de 7 votants vous pouvez observer des groupes d'opinion se former."
    "help_4": "Tentez de faire émerger un consensus en proposant de nouveaux points de vue (Les groupe d'opinion évoluent en temps réel)."
    "moder": "Modération :"
    "donnée": "Données :"
  nl:
    "titre_message": "Neem deel aan het debat"
    "texte_message_1": "Om deel te nemen aan het debat"
    "lien_message_1": "inloggen met uw account"
    "texte_message_2": "of"
    "lien_message_2": "meld je aan"
    "titre_help_1": "Hoe werkt het ?"
    "titre_help_2": "Welkom bij een nieuw soort discussie."
    "help_1": "Stem op de meningen van anderen."
    "help_2": "Expresseer de jouwe."
    "help_3": "Van 7 kiezers kun je groepen opinievorming observeren."
    "help_4": "Probeer consensus te bereiken door nieuwe standpunten voor te stellen (de opiniegroepen evolueren in real time)."
    "moder": "Matiging :"
    "donnée": "Gegevens :"

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
